// Emits supabase/forge_seed.sql from src/lib/forge/challenges.ts.
// Run:  npx tsx scripts/forge-seed.ts
import { writeFileSync } from "fs";
import { resolve } from "path";
import { FORGE_CHALLENGES } from "../src/lib/forge/challenges";

const esc = (s: string) => s.replace(/'/g, "''");
const lit = (s: string) => `'${esc(s)}'`;
const arr = (xs: string[]) => `ARRAY[${xs.map(lit).join(",")}]::text[]`;
const json = (v: unknown) => `'${esc(JSON.stringify(v))}'::jsonb`;
const bool = (b: boolean) => (b ? "true" : "false");

const lines: string[] = [
  "-- Generated by scripts/forge-seed.ts — do not hand-edit.",
  "-- Source of truth: src/lib/forge/challenges.ts",
  "",
  "begin;",
  "",
  "-- Wipe and re-seed all challenges. Submissions are NOT touched.",
  "delete from public.forge_challenges;",
  "",
];

for (const c of FORGE_CHALLENGES) {
  lines.push(
    `insert into public.forge_challenges
  (week_number, track, title, brief, skill_forced, rubric, submission_formats, max_file_mb, difficulty, is_pro_only)
values (
  ${c.week_number},
  ${lit(c.track)},
  ${lit(c.title)},
  ${lit(c.brief)},
  ${lit(c.skill_forced)},
  ${json(c.rubric)},
  ${arr(c.submission_formats)},
  ${c.max_file_mb},
  ${lit(c.difficulty)},
  ${bool(c.is_pro_only)}
);
`,
  );
}

lines.push("commit;", "");

const out = resolve(process.cwd(), "supabase/forge_seed.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`Wrote ${FORGE_CHALLENGES.length} rows to ${out}`);
